# file: .air.toml

root = "."
tmp_dir = "bin"

[build]
bin = "./bin/Sudoku.exe"
cmd = "templ generate && npm run dev &&  go build -o ./bin/Sudoku.exe . "
delay = 1000
exclude_dir = ["static", "node_modules"]
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
kill_delay = "0s"
log = "./logs/build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = true
